# Generated by Django 4.1.11 on 2023-12-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_calmsongs_happysongs_motivationalsongs_sadsongs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calmsongs",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio_files"),
        ),
        migrations.AlterField(
            model_name="calmsongs",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
        migrations.AlterField(
            model_name="motivationalsongs",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio_files"),
        ),
        migrations.AlterField(
            model_name="motivationalsongs",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
